name: edge-centric
channels:
  - conda-forge
dependencies:
  - python=3.13.2
  - pandas==2.3.1
  - matplotlib==3.10.3
  - toml==0.10.2
  - pyyaml==6.0.2
  - cachetools==5.5.2
  - asyncache==0.3.1
  - openai==1.97.0
  - tiktoken==0.9.0
  - pydantic==2.11.7
  - networkx==3.5
  - transformers==4.53.2
  - jinja2==3.1.6
  - thefuzz==0.22.1
  - sortedcontainers==2.4.0
  - pip:
    - tree-sitter-rust==0.23.2
    - tree-sitter==0.24.0
    - tree-sitter-cpp==0.23.4
    - tree-sitter-c==0.23.5
