name: edge-centric
channels:
  - conda-forge
dependencies:
  - python=3.13.2
  - pandas==2.3.1
  - matplotlib==3.10.3
  - toml==0.10.2
  - pyyaml==6.0.2
  - cachetools==5.5.0
  - asyncache==0.3.1
  - openai==1.52.2
  - tiktoken
  - pydantic==2.9.2
  - networkx==3.4.2
  - transformers==4.46.2
  - jinja2==3.1.4
  - thefuzz==0.22.1
  - sortedcontainers==2.4.0
  - pip:
    - tree-sitter-rust==0.23.0
    - tree-sitter==0.24.0
    - tree-sitter-cpp==0.23.1
    - tree-sitter-c==0.23.1
